### PR TITLE
Added Lw3

### PR DESCRIPTION
**Pull request by RylkovKirill**
Hello, you can view the result of the lab work by clicking on this link.
https://drive.google.com/file/d/15PnR3c8DG3PyRJdoRi4SOSJNKYYtI6FF/view

### CODE REVIEW

**Review by gmltA — CHANGES_REQUESTED** [review]
Wasn't actually able to log in successfully. Getting 'Login failed' with any creds.

**Comment by gmltA** [comment]
> Wasn't actually able to log in successfully. Getting 'Login failed' with any creds.

**Comment by gmltA** [comment]
> Wasn't actually able to log in successfully. Getting 'Login failed' with any creds.

image

**Review by gmltA — APPROVED** [review]
Good luck!

**Comment by RylkovKirill** [comment]
> Good luck!

Thanks!

**Pull request merged**
